# Generated by Django 5.2.2 on 2025-06-08 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EngD_project", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="wordsearchhistory",
            name="antonyms",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wordsearchhistory",
            name="pronunciation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="wordsearchhistory",
            name="synonyms",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wordsearchhistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
